[profile.default]
libs = ["lib"]
names = true
sizes = true
via_ir = true
optimizer = true
optimizer_runs = 200
bytecode_hash = "none"
evm_version = "cancun"

[profile.default.invariant]
runs = 1024
depth = 32
fail_on_revert = true

[profile.default.fmt]
wrap_comments = true


[profile.build]
test = "/dev/null"
script = "/dev/null"


[profile.test]
via-ir = false

[etherscan]
kaia = { key = "${KAIASCAN_KEY}", url = "https://mainnet-oapi.kaiascan.io/api" }


# See more config options https://github.com/foundry-rs/foundry/tree/master/crates/config
